import {Platform, StyleSheet} from 'react-native';
import {useContext} from 'react';
import {AppThemeContext} from '../../context/themeContext';

const useAskAiStyles = () => {
  const {theme, isDarkMode} = useContext(AppThemeContext);
  const styles = StyleSheet.create({
    flex: {
      flex: 1,
    },
    hidden: {
      display: 'none',
    },
    container: {
      flex: 1,
      width: theme.width,
      padding: 12,
      paddingBottom: 0,
    },
    title: {
      marginTop: 48,
      marginBottom: 24,
      marginLeft: 14,
      fontSize: 25,
      color: theme.titleColor,
      fontFamily: theme.fontMedium,
      textAlign: 'left',
    },
    titleRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
    },
    searchInput: {
      width: '100%',
      paddingHorizontal: 12,
      marginVertical: 8,
      backgroundColor: theme.loginInputBgColor,
      borderRadius: 4,
      fontFamily: theme.font,
      fontSize: theme.responsiveFontSize * 0.925,
      color: theme.textColor,
    },
    inputWrapper: {
      flexDirection: 'row',
      position: 'relative',
      height: 60,
    },
    placeholderText: {
      position: 'absolute',
      top: 18,
      left: 14,
      color: theme.searchPlaceHolderColor,
      fontSize: 16,
      fontFamily: theme.font,
    },
    inputText: {
      marginHorizontal: 14,
      fontFamily: theme.fontMedium,
      color: theme.titleColor,
      fontSize: 18,
      marginBottom: 4,
    },
    menuContainer: {
      width: '100%',
      marginVertical: theme.boxesVerticalMargin,
      flexDirection: 'row',
      alignSelf: 'center',
      alignItems: 'center',
      backgroundColor: theme.subMenuBgColor,
      borderRadius: 4,
    },
    menuButton: {
      width: '50%',
      backgroundColor: 'transparent',
      borderRadius: 4,
      overflow: 'hidden',
    },
    historyButtonWrapper: {
      position: 'absolute',
      right: 14,
      alignSelf: 'center',
    },
    historyButton: {
      width: 21,
      height: 23,
      marginBottom: 4,
      tintColor: '#A3A3A3',
    },
    activeButton: {
      backgroundColor: theme.activeWhite,
      borderColor: theme.subMenuBgColor,
      borderWidth: 2,
      borderRadius: 4,
    },
    menuText: {
      marginVertical: 5,
      textAlign: 'center',
      fontSize: 14,
      fontFamily: theme.font,
      color: theme.secondaryTextColor,
    },
    activeText: {
      fontFamily: theme.fontMedium,
      color: theme.subMenuTextColor,
    },
    searchButton: {
      width: 55,
      height: 44,
      marginHorizontal: 8,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.orange,
      borderRadius: 4,
    },
    searchButtonImage: {
      width: 12,
      height: 12,
      alignSelf: 'center',
      tintColor: '#FFFFFF',
    },
    searchButtonText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontFamily: theme.fontMedium,
    },
    row: {
      flexDirection: 'row',
    },
    emptyIcon: {
      width: 48,
      height: 48,
      marginLeft: 6,
      borderRadius: 24,
      alignSelf: 'flex-start',
      backgroundColor: theme.boxesBackgroundColor,
    },
    emptyTitle: {
      width: 125,
      height: 20,
      marginHorizontal: 14,
      alignSelf: 'center',
      borderRadius: 2,
      backgroundColor: theme.boxesBackgroundColor,
    },
    emptySecondTitle: {
      width: 100,
      marginBottom: 8,
      marginTop: 16,
      marginHorizontal: 26,
      alignSelf: 'flex-start',
    },
    emptyContent: {
      width: '100%',
      height: 400,
      backgroundColor: theme.boxesBackgroundColor,
      borderRadius: 3,
      alignSelf: 'center',
    },
    resultsContainer: {
      position: 'relative',
      backgroundColor: theme.boxesBackgroundColor,
      marginBottom: 32,
      padding: 12,
      borderRadius: 4,
    },
    valueBoxContainer: {
      width: '100%',
      marginBottom: 8,
      justifyContent: 'center',
      alignSelf: 'center',
    },
    boxTitle: {
      marginVertical: theme.boxesVerticalMargin,
      marginHorizontal: 14,
      color: theme.titleColor,
      fontSize: 16,
      fontFamily: theme.fontMedium,
      textTransform: 'capitalize',
    },
    content: {
      width: '100%',
      alignSelf: 'center',
      padding: 14,
      fontSize: 14,
      fontFamily: theme.font,
      color: theme.textColor,
      backgroundColor: theme.tableHeaderColor,
    },
    iconImage: {
      width: 48,
      height: 48,
      alignSelf: 'flex-start',
      overflow: 'hidden',
    },
    imageBackground: {
      width: 48,
      height: 48,
      marginVertical: 24,
      marginLeft: 6,
      borderRadius: 24,
      justifyContent: 'center',
      backgroundColor: theme.tableHeaderColor,
      overflow: 'hidden',
    },
    coinName: {
      fontSize: 16,
      color: theme.titleColor,
      fontFamily: theme.fontMedium,
      marginHorizontal: 14,
      alignSelf: 'center',
      textTransform: 'capitalize',
    },
    disabledButton: {
      backgroundColor: theme.secondaryGrayColor,
    },
    historySection: {
      width: '100%',
    },
    cleanButton: {
      flexDirection: 'row',
      marginVertical: 8,
      alignSelf: 'flex-end',
      alignItems: 'center',
    },
    trashIcon: {
      width: 14,
      height: 14,
      marginRight: 6,
      tintColor: theme.secondaryTextColor,
      alignSelf: 'center',
    },
    cleanText: {
      textAlign: 'right',
      color: theme.secondaryTextColor,
      fontSize: 14,
      fontFamily: theme.font,
    },
    historyMenuContainer: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 4,
      backgroundColor: theme.subMenuBgColor,
    },
    historyMenuButton: {
      backgroundColor: 'transparent',
      borderRadius: 4,
      overflow: 'hidden',
    },
    historyItemsContainer: {
      width: '100%',
      height: theme.height * 0.55,
      marginVertical: 8,
      padding: Platform.OS === 'ios' ? 10 : 0,
      overflow: 'scroll',
    },
    historyItem: {
      position: 'relative',
      width: '100%',
      marginBottom: 4,
      flexDirection: 'row',
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderRadius: 3,
      alignItems: 'center',
      backgroundColor: theme.boxesBackgroundColor,
    },
    historyItemLogo: {
      width: 38,
      height: 38,
      borderRadius: 19,
    },
    historyItemImageBackground: {
      width: 42,
      height: 42,
      borderRadius: 21,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.thirdBoxesBgColor,
    },
    historyItemName: {
      marginHorizontal: 10,
      fontSize: 16,
      color: theme.textColor,
      fontFamily: theme.fontMedium,
      textTransform: 'uppercase',
    },
    rightArrow: {
      position: 'absolute',
      right: 8,
      width: 14,
      height: 14,
      marginHorizontal: 8,
      tintColor: theme.secondaryGrayColor,
    },
    noContentMessage: {
      margin: theme.boxesVerticalMargin,
      fontSize: 14,
      color: theme.secondaryTextColor,
      alignSelf: 'center',
      fontFamily: theme.font,
    },
    closeButton: {
      position: 'absolute',
      top: 8,
      right: 24,
      width: 40,
      height: 40,
    },
    closeButtonImage: {
      width: 24,
      height: 24,
      marginTop: 6,
      marginLeft: 12,
      tintColor: theme.secondaryGrayColor,
      alignSelf: 'center',
    },
    mainResultsContainer: {
      width: '100%',
      padding: 10,
      backgroundColor: theme.boxesBackgroundColor,
      borderRadius: 3,
    },
    resultsTitle: {
      marginRight: 12,
      fontSize: 12,
      fontFamily: theme.font,
      color: isDarkMode ? '#A3A3A3' : '#808080',
      alignSelf: 'center',
    },
    titleLine: {
      width: '75%',
      alignSelf: 'center',
      borderBottomColor: theme.secondaryGrayColor,
      borderBottomWidth: 1,
      marginVertical: 8,
    },
    loadMoreText: {
      width: '25%',
      fontSize: 12,
      fontFamily: theme.fontMedium,
      color: theme.secondaryTextColor,
      alignSelf: 'center',
    },
  });
  return styles;
};

export default useAskAiStyles;
