import {useContext} from 'react';
import {AppThemeContext} from '../../context/themeContext';

/* eslint-disable prettier/prettier */
const {StyleSheet} = require('react-native');

const useLoaderStyles = () => {
  const {isDarkMode, theme} = useContext(AppThemeContext);
  const styles = StyleSheet.create({
    loaderContainer: {
      flex: 1,
      width: '100%',
      minHeight: theme.height * 0.25,
      padding: '25%',
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
    },
    loadingText: {
      marginTop: 10,
      color: theme.textColor,
      fontSize: theme.responsiveFontSize * 0.75,
    },
    centeredContainer: {
      ...StyleSheet.absoluteFillObject,
      padding: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.mainBackgroundColor,
    },
    fullViewContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 20,
    },
    loader: {
      width: 40,
      height: 40,
    },
    container: {
      flexDirection: 'row',
      width: '100%',
      paddingLeft: 12,
      paddingVertical: 16,
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: theme.skeletonLoaderBg,
      borderRadius: 4,
    },
    avatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
      marginLeft: 10,
      alignSelf: 'center',
      backgroundColor: theme.thirdBoxesBgColor,
    },
    textContainer: {
      flex: 1,
      alignItems: 'flex-start',
    },
    textLine: {
      height: 16,
      width: '85%',
      borderRadius: 4,
      marginVertical: 4,
      marginHorizontal: 14,
      backgroundColor: theme.thirdBoxesBgColor,
    },
    circle: {
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: 'center',
      justifyContent: 'center',
      margin: 10,
      marginBottom: 15,
      alignSelf: 'center',
      backgroundColor: theme.skeletonLoaderBg,
    },
    alertsLoader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 4,
      padding: 6,
      paddingVertical: 8,
    },
    chartBar: {
      width: 12,
      backgroundColor: theme.thirdBoxesBgColor,
    },
    trendLineContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '80%',
      height: 2,
      marginBottom: 10,
    },
    trendLineSegment: {
      width: '20%',
      height: 2,
      borderTopWidth: 2,
      borderRightWidth: 2,
      borderColor: theme.thirdBoxesBgColor,
    },
    barsContainer: {
      width: '80%',
      minHeight: 240,
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      borderEndWidth: 4,
      borderBottomWidth: 4,
      borderColor: theme.thirdBoxesBgColor,
    },
    chartContainer: {
      width: '100%',
      paddingTop: 24,
      alignSelf: 'center',
      backgroundColor: theme.skeletonLoaderBg,
      borderRadius: 4,
      alignItems: 'center',
    },
    textLoaderContainer: {
      width: '100%',
      padding: 8,
      justifyContent: 'flex-start',
    },
    title: {
      height: 20,
      backgroundColor: theme.thirdBoxesBgColor,
      marginBottom: 8,
      width: '60%',
      borderRadius: 2,
    },
    image: {
      width: 150,
      height: '100%',
      backgroundColor: theme.thirdBoxesBgColor,
    },
    circleChart: {
      width: 220,
      height: 220,
      marginHorizontal: 16,
      backgroundColor: 'transparent',
      borderRadius: 110,
      borderWidth: 12,
      borderColor: theme.thirdBoxesBgColor,
    },
    timelineEvent: {
      borderRadius: 2,
      borderWidth: 3,
      borderColor: theme.thirdBoxesBgColor,
      width: '80%',
      height: '90%',
      marginLeft: 20,
      padding: 12,
    },
    timelineCircle: {
      width: 18,
      height: 18,
      marginLeft: 20,
      marginVertical: 30,
      borderRadius: 9,
    },
    timelineLine: {
      position: 'absolute',
      left: 40,
      bottom: 0,
      top: 20,
      width: 2,
      height: '95%',
      backgroundColor: theme.thirdBoxesBgColor,
    },
    mainImageLoader: {
      width: 320,
      height: 300,
      marginTop: theme.boxesVerticalMargin,
      alignSelf: 'center',
    },
    square: {
      width: 50,
      height: 50,
      marginLeft: 10,
      alignSelf: 'center',
      backgroundColor: theme.thirdBoxesBgColor,
    },
    dappsLoader: {
      flex: 1,
      padding: 10,
      backgroundColor: theme.skeletonLoaderBg,
    },
    row: {
      flex: 1,
      width: '100%',
      flexDirection: 'row',
      paddingVertical: 4,
    },
    menuItem: {
      width: 60,
      height: 60,
      marginHorizontal: 4,
      backgroundColor: theme.thirdBoxesBgColor,
    },
    speedometerContainer: {
      width: '100%',
      marginVertical: 8,
      padding: 10,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      backgroundColor: theme.skeletonLoaderBg,
      borderRadius: 4,
    },
    halfCircle: {
      backgroundColor: theme.thirdBoxesBgColor,
      borderTopLeftRadius: 100,
      borderTopRightRadius: 100,
      overflow: 'hidden',
    },
    needle: {
      position: 'absolute',
      top: 115,
      left: 100,
      backgroundColor: theme.chartsAxisColor,
      borderRadius: 1,
    },
    deepDiveCard: {
      width: 220,
      height: 270,
      padding: 10,
      margin: 8,
      justifyContent: 'center',
      backgroundColor: theme.thirdBoxesBgColor,
      borderRadius: 6,
    },
    cardImage: {
      width: '100%',
      height: 135,
      borderRadius: 3,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    cardTitle: {
      height: 18,
      marginTop: 10,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    date: {
      height: 14,
      marginTop: 4,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    headerContainer: {
      width: '100%',
      height: theme.width * 0.6,
      padding: 10,
      paddingTop: 0,
      marginBottom: 16,
    },
    headerImage: {
      width: '100%',
      height: '70%',
      marginTop: 8,
      borderRadius: 6,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    headerContent: {
      padding: 10,
    },
    headerTitle: {
      height: 22,
      marginBottom: 4,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    newsItem: {
      flexDirection: 'row',
      padding: 10,
      marginVertical: 4,
    },
    thumbnail: {
      width: 60,
      height: 60,
      borderRadius: 6,
      marginRight: 12,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    newsContent: {
      flex: 1,
      justifyContent: 'center',
    },
    newsTitle: {
      height: 14,
      marginBottom: 4,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    newsDate: {
      height: 12,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
    macroCard: {
      width: 162.5,
      height: 190,
      padding: 10,
      margin: 8,
      justifyContent: 'center',
      backgroundColor: theme.thirdBoxesBgColor,
      borderRadius: 6,
    },
    macroCardImage: {
      width: '100%',
      height: 80,
      borderRadius: 3,
      backgroundColor: isDarkMode ? '#52525B' : '#D9D9D9',
    },
  });
  return styles;
};

export default useLoaderStyles;
