export const icons = {
  '1INCH': require('../../../../../../../../assets/images/fundamentals/competitors/icons/1INCH.png'),
  AAVE: require('../../../../../../../../assets/images/fundamentals/competitors/icons/AAVE.png'),
  CARDANO: require('../../../../../../../../assets/images/fundamentals/competitors/icons/ADA.png'),
  ALGORAND: require('../../../../../../../../assets/images/fundamentals/competitors/icons/ALGO.png'),
  'API 3': require('../../../../../../../../assets/images/fundamentals/competitors/icons/API3.png'),
  ARBITRUM: require('../../../../../../../../assets/images/fundamentals/competitors/icons/ARB.png'),
  COSMOS: require('../../../../../../../../assets/images/fundamentals/competitors/icons/ATOM.png'),
  AVALANCHE: require('../../../../../../../../assets/images/fundamentals/competitors/icons/AVAX.png'),
  'BAND PROTOCOL': require('../../../../../../../../assets/images/fundamentals/competitors/icons/BAND.png'),
  BITCOIN: require('../../../../../../../../assets/images/fundamentals/competitors/icons/BTC.png'),
  'PANCAKE SWAP': require('../../../../../../../../assets/images/fundamentals/competitors/icons/CAKE.png'),
  POLKADOT: require('../../../../../../../../assets/images/fundamentals/competitors/icons/DOT.png'),
  DYDX: require('../../../../../../../../assets/images/fundamentals/competitors/icons/DYDX.png'),
  ETHEREUM: require('../../../../../../../../assets/images/fundamentals/competitors/icons/ETH.png'),
  'FETCH.AI': require('../../../../../../../../assets/images/fundamentals/competitors/icons/FET.png'),
  FANTOM: require('../../../../../../../../assets/images/fundamentals/competitors/icons/FTM.png'),
  'FRAX FINANCE': require('../../../../../../../../assets/images/fundamentals/competitors/icons/FXS.png'),
  GMX: require('../../../../../../../../assets/images/fundamentals/competitors/icons/GMX.png'),
  KASPA: require('../../../../../../../../assets/images/fundamentals/competitors/icons/KAS.png'),
  'LIDO FINANCE': require('../../../../../../../../assets/images/fundamentals/competitors/icons/LDO.png'),
  CHAINLINK: require('../../../../../../../../assets/images/fundamentals/competitors/icons/LINK.png'),
  MATIC: require('../../../../../../../../assets/images/fundamentals/competitors/icons/MATIC.png'),
  'NEAR PROTOCOL': require('../../../../../../../../assets/images/fundamentals/competitors/icons/NEAR.png'),
  OCEAN: require('../../../../../../../../assets/images/fundamentals/competitors/icons/OCEAN.png'),
  OPTIMISM: require('../../../../../../../../assets/images/fundamentals/competitors/icons/OP.png'),
  PENDLE: require('../../../../../../../../assets/images/fundamentals/competitors/icons/PENDLE.png'),
  QUANT: require('../../../../../../../../assets/images/fundamentals/competitors/icons/QNT.png'),
  RENDER: require('../../../../../../../../assets/images/fundamentals/competitors/icons/RNDR.png'),
  'ROCKET POOL': require('../../../../../../../../assets/images/fundamentals/competitors/icons/RPL.png'),
  SOLANA: require('../../../../../../../../assets/images/fundamentals/competitors/icons/SOL.png'),
  SUSHI: require('../../../../../../../../assets/images/fundamentals/competitors/icons/SUSHI.png'),
  UNI: require('../../../../../../../../assets/images/fundamentals/competitors/icons/UNI.png'),
  VELO: require('../../../../../../../../assets/images/fundamentals/competitors/icons/VELO.png'),
  STELLAR: require('../../../../../../../../assets/images/fundamentals/competitors/icons/XLM.png'),
  RIPPLE: require('../../../../../../../../assets/images/fundamentals/competitors/icons/XRP.png'),
};
