import {useContext} from 'react';
import {Platform, StyleSheet} from 'react-native';
import {AppThemeContext} from '../../context/themeContext';

const useIntroductorySlidesStyles = () => {
  const {theme} = useContext(AppThemeContext);
  const styles = StyleSheet.create({
    sectionContainer: {
      flex: 1,
      width: theme.width,
      height: theme.height,
      backgroundColor: '#171717',
    },
    slide: {
      flex: 1,
      position: 'relative',
      width: theme.width,
      height: theme.height,
      alignSelf: 'center',
      alignItems: 'center',
      paddingTop: 40,
    },
    mainImage: {
      width: 350,
      height: 200,
      marginHorizontal: 18,
    },
    contentContainer: {
      width: '100%',
      marginVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    items: {
      paddingHorizontal: 22,
    },
    title: {
      textAlign: 'center',
      alignSelf: 'center',
      fontFamily: theme.fontMedium,
      fontSize: 25,
      lineHeight: 30,
      color: '#FFFFFF',
    },
    subtitle: {
      marginVertical: 6,
      fontFamily: theme.fontSemibold,
      fontSize: 14,
      color: '#FAFAFA',
      textAlign: 'center',
      alignSelf: 'center',
    },
    informationItem: {
      width: '100%',
      marginVertical: 4,
      flexDirection: 'row',
      alignItems: 'center',
    },
    informationIcon: {
      width: 35,
      height: 30,
      marginHorizontal: 4,
      tintColor: '#FC5404',
      alignSelf: 'flex-start',
    },
    informationText: {
      maxWidth: 300,
      fontSize: 14,
      fontFamily: theme.font,
      color: '#FAFAFA',
      textAlign: 'left',
      alignSelf: 'center',
    },
    skipContainer: {
      position: 'absolute',
      width: '100%',
      paddingHorizontal: 12,
      bottom: Platform.OS === 'ios' ? 120 : 68,
    },
    boldInformativeText: {
      width: '100%',
      marginTop: 24,
      marginBottom: 12,
      fontFamily: theme.fontSemibold,
      fontSize: 16,
      color: '#FF6C0D',
      alignSelf: 'center',
      textAlign: 'center',
    },
    skipButton: {
      alignSelf: 'center',
      fontFamily: theme.font,
      color: '#A3A3A3',
      fontSize: 12,
      textAlign: 'center',
    },
    carouselContainer: {
      flex: 1,
      width: '100%',
    },
    carouselScrollView: {
      flex: 1,
      width: '100%',
    },
    pagination: {
      flexDirection: 'row',
      position: 'absolute',
      bottom: 12,
      paddingVertical: 4,
      paddingHorizontal: 12,
      alignSelf: 'center',
      alignItems: 'center',
      borderRadius: 15,
      backgroundColor: '#525252',
    },
    dot: {
      height: 5,
      width: 5,
      borderRadius: 2.5,
      backgroundColor: '#A3A3A3',
      margin: 6,
    },
    activeDot: {
      height: 9,
      width: 9,
      borderRadius: 4.5,
      backgroundColor: '#FFFFFF',
    },
    exploreButton: {
      width: '100%',
      marginTop: 32,
      padding: 8,
      alignItems: 'center',
      borderRadius: 4,
    },
    buttonText: {
      fontSize: 16,
      fontFamily: theme.fontSemibold,
      color: '#FAFAFA',
      textAlign: 'center',
    },
    popUpModal: {
      position: 'relative',
      width: '100%',
      marginTop: 20,
      paddingVertical: 10,
      backgroundColor: '#404040',
      borderRadius: 4,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    popUpTitle: {
      fontFamily: theme.fontSemibold,
      color: '#FAFAFA',
      fontSize: 14,
      textAlign: 'center',
    },
    popUpText: {
      marginTop: 6,
      marginBottom: 16,
      marginHorizontal: 16,
      paddingHorizontal: 8,
      fontFamily: theme.font,
      color: '#FAFAFA',
      lineHeight: 22,
      fontSize: 14,
      textAlign: 'center',
    },
    row: {
      width: '100%',
      flexDirection: 'row',
    },
    popUpSkip: {
      paddingHorizontal: 20,
      textAlign: 'left',
      color: '#A3A3A3',
      fontFamily: theme.font,
      fontSize: 10,
    },
    popUpNext: {
      textAlign: 'right',
      position: 'absolute',
      right: 20,
      alignSelf: 'flex-end',
      color: '#FF6C0D',
      fontFamily: theme.font,
      fontSize: 14,
    },
    popUpDot: {
      width: 3,
      height: 3,
      margin: 3,
      borderRadius: 1.5,
      backgroundColor: '#737373',
    },
    popUpActiveDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
    },
    dotsContainer: {
      marginHorizontal: 22,
      marginVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    triangle: {
      position: 'absolute',
      left: 150,
      width: 24,
      height: 24,
      tintColor: '#404040',
    },
    popUpsOverlay: {
      position: 'relative',
      width: '100%',
      paddingHorizontal: 12,
      height: theme.height,
      backgroundColor: 'rgba(10,10,10,0.6)',
      zIndex: 1000,
    },
    subscribePopUpsButton: {
      width: '80%',
      marginVertical: 12,
      paddingVertical: 6,
      paddingHorizontal: 24,
      alignItems: 'center',
      backgroundColor: '#FF6C0D',
      borderRadius: 4,
    },
    popUpsButtonText: {
      fontFamily: theme.fontMedium,
      fontSize: 14,
    },
    nextRightArrow: {
      position: 'absolute',
      right: 8.5,
      width: 6,
      height: 10,
      tintColor: '#FF6C0D',
    },
    popUpPressableOverlay: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
    },
    invisiblePressable: {
      width: '100%',
      height: Platform.OS === 'ios' ? 240 : 170,
      backgroundColor: 'transparent',
      alignSelf: 'flex-start',
      justifyContent: 'flex-start',
    },
    bottomTransparentButton: {
      position: 'absolute',
      bottom: '-15%',
      width: '20%',
      height: 100,
      zIndex: 30,
    },
    categoriesTape: {
      position: 'absolute',
      top: 135,
      left: -150,
      height: 70,
      overflow: 'visible',
      zIndex: 200,
    },
  });
  return styles;
};

export default useIntroductorySlidesStyles;
