import {StyleSheet} from 'react-native';
import {useContext} from 'react';
import {AppThemeContext} from '../../../context/themeContext';

const usePackageSubscriptionStyles = () => {
  const {theme, isDarkMode} = useContext(AppThemeContext);
  const styles = StyleSheet.create({
    gradient: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    backgroundContainer: {
      backgroundColor: theme.mainBackgroundColor,
    },
    container: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: theme.boxesBackgroundColor,
    },
    scrollViewContent: {
      paddingBottom: 0,
    },
    innerContainer: {
      flex: 1,
      width: theme.width,
      paddingHorizontal: 10,
      paddingBottom: 10,
      paddingTop: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.mainBackgroundColor,
    },
    flex: {
      flex: 1,
    },
    mainTitle: {
      marginTop: 11,
      marginBottom: 25,
      marginLeft: 15,
      marginVertical: theme.titlesVerticalMargin,
      color: theme.titleColor,
      fontSize: theme.titleFontSize * 1.25,
      fontFamily: theme.fontSemibold,
      textAlign: 'center',
      flexDirection: 'row',
      alignSelf: 'flex-start',
    },
    smallSubtitle: {
      color: theme.smallSubtitleColor,
      fontFamily: theme.fontMedium,
      fontSize: 16,
      alignSelf: 'flex-start',
      marginLeft: 15,
    },
    description: {
      marginVertical: theme.boxesVerticalMargin,
      marginTop: 4,
      marginHorizontal: 23.5,
    },
    secondaryText: {
      color: theme.textColor,
      fontSize: theme.responsiveFontSize * 0.82,
      fontFamily: theme.font,
      lineHeight: 22,
      textAlign: 'left',
      marginRight: 29,
    },
    preTertiaryText: {
      color: theme.subscriptions.secondaryText,
      fontSize: theme.responsiveFontSize * 0.75,
      fontFamily: theme.font,
      lineHeight: 22,
      textAlign: 'left',
      marginRight: 10,
    },
    tertiaryText: {
      color: theme.subscriptions.secondaryText,
      fontSize: theme.responsiveFontSize * 0.75,
      fontFamily: theme.font,
      lineHeight: 15,
      textAlign: 'center',
      marginRight: 10,
      marginTop: 1,
    },
    textRow: {
      textAlign: 'center',
      flexDirection: 'row', // Arrange icon and text in a row
      alignItems: 'center', // Vertically center the items
      marginBottom: 10,
      marginRight: 10,
    },
    textCenteredRow: {
      textAlign: 'center',
      marginBottom: 5,
    },
    textRowContainer: {
      marginBottom: 15,
    },
    packagesContainer: {
      width: '104%',
      marginBottom: 16,
      paddingTop: 2,
      paddingLeft: 10,
      paddingRight: 10,
      paddingBottom: 10,
    },
    itemContainer: {
      flex: 1,
      flexDirection: 'column', // Change to column
      alignItems: 'flex-start', // Align items to the start
      padding: 10,
      backgroundColor: theme.backgroundSubscriptionsModal,
      marginVertical: 5,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    selectedItem: {
      borderColor: theme.activeOrange,
    },
    itemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
    },
    circleContainer: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.activeOrange,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'transparent',
      marginRight: 8,
    },
    subCircleContainer: {
      width: 18,
      height: 18,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: theme.activeOrange,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'transparent',
      marginRight: 8,
      marginLeft: 3,
    },
    tickImage: {
      width: '110%',
      height: '110%',
      position: 'absolute',
    },
    subTickImage: {
      width: '110%',
      height: '110%',
      position: 'absolute',
    },
    itemIcon: {
      width: 27,
      height: 22,
      marginRight: 10,
      marginLeft: 5,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    title: {
      color: theme.subscriptions.text,
      fontSize: theme.titleFontSize * 0.91,
      fontFamily: theme.fontSemibold,
      flex: 1,
    },
    priceContainer: {
      alignItems: 'flex-end',
    },
    priceText: {
      color: theme.subscriptions.text,
      fontSize: theme.responsiveFontSize * 1.1,
      fontFamily: theme.fontBold,
    },
    perMonthText: {
      color: theme.subscriptions.secondaryText,
      fontSize: theme.responsiveFontSize * 0.8,
      fontFamily: theme.font,
      textAlign: 'right',
    },
    linearGradient: {
      width: '100%',
      height: 50,
      borderRadius: 3,
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 10,
    },
    purchaseButton: {
      width: '100%',
      paddingVertical: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    purchaseButtonText: {
      color: '#FFFFFF',
      fontSize: theme.titleFontSize * 0.9,
      fontFamily: theme.fontSemibold,
    },
    alignStart: {
      alignSelf: 'flex-start',
      marginVertical: theme.boxesVerticalMargin,
    },
    smallTickIcon: {
      width: 11,
      height: 11,
      marginRight: 8,
    },
    fixedFooter: {
      position: 'absolute',
      bottom: 0,
      width: '100%',
      backgroundColor: theme.mainBackgroundColor,
      padding: 10,
      alignItems: 'center',
    },
    footerTextContainer: {
      alignItems: 'center',
      marginTop: -5,
      marginBottom: 30,
    },
    subOptionsContainer: {
      marginTop: 10,
      marginLeft: 0,
      flexDirection: 'column', // Ensure sub options are stacked vertically
      alignItems: 'flex-start', // Align sub options to the start
    },
    subOption: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 5,
    },
    subOptionText: {
      color: theme.subscriptions.text,
      fontSize: theme.responsiveFontSize * 0.75,
      fontFamily: theme.font,
      marginLeft: 9,
    },
    subOptionShowMore: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 5,
    },
    subOptionTextShowMore: {
      color: theme.activeOrange,
      fontSize: theme.responsiveFontSize * 0.75,
      fontFamily: theme.font,
      paddingLeft: 37,
      textDecorationLine: 'underline',
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      width: '95%',
      backgroundColor: theme.backgroundSubscriptionsModal,
      padding: 20,
      borderRadius: 10,
      marginTop: -20,
    },
    modalOption: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 7,
      marginLeft: 15,
    },
    doneButton: {
      marginTop: 20,
      alignItems: 'center',
    },
    doneButtonText: {
      color: theme.activeOrange,
      fontSize: theme.responsiveFontSize * 0.97,
      fontFamily: theme.fontLight,
      textDecorationLine: 'underline',
    },
    modalTitle: {
      color: theme.subscriptions.text,
      fontSize: theme.titleFontSize * 0.8,
      fontFamily: theme.font,
      flex: 1,
    },
    subModalCircleContainer: {
      width: 18,
      height: 18,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: theme.activeOrange,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'transparent',
      marginRight: 8,
    },
    tickModalImage: {
      width: '113%',
      height: '113%',
      position: 'absolute',
    },
    itemModalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      marginBottom: 10,
      paddingTop: 20,
    },
    modalByCategoryTitle: {
      color: theme.subscriptions.text,
      fontSize: theme.titleFontSize * 0.92,
      fontFamily: theme.fontSemibold,
      flex: 1,
    },
    textFounders: {
      color: theme.subscriptions.title,
      fontSize: theme.responsiveFontSize * 0.91,
      fontFamily: theme.fontUnboundedMedium,
      textAlign: 'center',
      lineHeight: 22,
      marginTop: 10,
    },
    bigTextFounders: {
      color: '#FF6C0D',
      fontSize: theme.responsiveFontSize * 1.3,
      fontFamily: theme.fontUnboundedMedium,
      textAlign: 'center',
      lineHeight: 32,
    },
    secondaryTextFounders: {
      color: theme.subscriptions.secondaryText,
      fontSize: theme.responsiveFontSize * 0.8,
      fontFamily: theme.font,
      lineHeight: 22,
      textAlign: 'center',
      margin: 25,
    },
    subscriptionImage: {
      width: 390,
      height: 270,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
    },
    textFoundersRow: {
      textAlign: 'center',
      alignSelf: 'center',
      flexDirection: 'row', // Arrange icon and text in a row
      alignItems: 'center', // Vertically center the items
      marginBottom: 5,
      marginRight: 10,
    },
    textWithIconTitle: {
      color: '#FF6C0D',
      fontFamily: theme.fontMedium,
      textAlign: 'center',
      fontSize: 18,
      marginLeft: 5,
      marginRight: 5,
    },
    textWithIconTitleNotPushed: {
      color: '#FF6C0D',
      fontFamily: theme.fontMedium,
      textAlign: 'center',
      fontSize: 18,
      marginLeft: 25,
      marginRight: 25,
    },
    textWithIconTitlePushed: {
      color: '#FF6C0D',
      fontFamily: theme.fontMedium,
      textAlign: 'center',
      fontSize: 18,
      marginLeft: 25,
      marginRight: 25,
      marginBottom: 35,
    },
    textWithIconTitlePushedv2: {
      color: '#FF6C0D',
      fontFamily: theme.fontMedium,
      textAlign: 'center',
      fontSize: 18,
      marginLeft: 25,
      marginRight: 25,
      marginBottom: 15,
    },
    textWithIconTitlePushedv3: {
      color: '#FF6C0D',
      fontFamily: theme.fontMedium,
      textAlign: 'center',
      fontSize: 18,
      marginLeft: 15,
      marginRight: 15,
      marginBottom: -10,
    },

    itemContainerCurrent: {
      borderWidth: 1,
      borderRadius: 8,
      borderColor: 'transparent',
      backgroundColor: theme.secondaryBgColor,
      padding: 16,
      marginBottom: 8,
    },
    itemRowCurrent: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    itemIconCurrent: {
      width: 30,
      height: 25,
      marginRight: 16,
      marginLeft: 8,
    },
    titleCurrent: {
      flex: 1,
      fontSize: 18,
      fontWeight: '600',
      fontFamily: theme.fontSemibold,
      color: theme.titleColor,
    },
    priceTextCurrent: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.titleColor,
    },
    perMonthTextCurrent: {
      fontSize: 12,
      color: '#888',
    },
    subOptionsContainerCurrent: {
      marginTop: 8,
      paddingHorizontal: 8,
    },
    subOptionCurrent: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 4,
      paddingHorizontal: 8,
      backgroundColor: 'transparent',
      borderRadius: 4,
      marginBottom: 4,
    },
    subOptionTextCurrent: {
      fontSize: 14,
      color: theme.mainTextColor,
      fontFamily: theme.font,
      paddingLeft: 38,
    },
    aboutButtonContainer: {
      flexDirection: 'row',
      marginTop: 5,
      marginBottom: -40,
      marginRight: -300,
    },
    aboutButton: {
      color: 'white',
      width: 21,
      height: 21,
    },
    discordContainer: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    discordIcon: {
      marginTop: 50,
      width: 78,
      height: 55,
    },
    discordOrangeText: {
      fontSize: 20,
      fontFamily: theme.fontMedium,
      color: theme.orange,
      textAlign: 'center',
      marginTop: 15,
      marginBottom: 15,
    },
    discordGreyText: {
      color: theme.discordGreyColor,
      fontFamily: theme.fontMedium,
      textAlign: 'center',
      marginTop: 5,
    },
    discordSubcontainer: {
      backgroundColor: 'transparent',
      width: '104%',
      padding: 10,
      borderRadius: 3,
      borderColor: '#444',
      borderWidth: 1,
      marginTop: 20,
      marginBottom: 50,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 15, // Add some space between the title and the token text
    },
    discordSmallIcon: {
      width: 35,
      height: 24,
      marginRight: 15,
      marginLeft: 3,
    },
    discordTitle: {
      color: theme.textColor,
      fontFamily: theme.fontMedium,
      fontSize: 16,
      marginTop: -7,
    },
    tokenRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    tokenText: {
      color: theme.textColor,
      fontSize: 16,
      flex: 1,
      marginLeft: 10,
      fontFamily: theme.font,
    },
    copyIcon: {
      width: 23,
      height: 26,
      marginLeft: 10,
    },
    foundersSmallSubtitle: {
      color: theme.smallSubtitleColor,
      fontFamily: theme.fontMedium,
      fontSize: 16,
      alignSelf: 'flex-start',
      marginLeft: 15,
      marginBottom: -20,
    },
    foundersMainTitle: {
      marginTop: 1,
      marginBottom: 25,
      marginLeft: 15,
      marginVertical: theme.titlesVerticalMargin,
      color: theme.titleColor,
      fontSize: theme.titleFontSize * 1.25,
      fontFamily: theme.fontSemibold,
      textAlign: 'center',
      flexDirection: 'row',
      alignSelf: 'flex-start',
    },
    scrollBarContainer: {
      backgroundColor: theme.boxesBackgroundColor,
      height: '30%',
      width: 5,
      marginBottom: 4,
      marginRight: Platform.OS === 'ios' ? 0 : 10,
      borderRadius: 2,
    },
    scrollBar: {
      backgroundColor: theme.scrollbarColor,
      width: 5,
      borderRadius: 4,
    },
  });
  return styles;
};

export default usePackageSubscriptionStyles;
