use_frameworks! :linkage => :static

source 'https://github.com/invertase/react-native-firebase.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '17.0'

pre_install do |installer|
  puts "Running pre_install hook to remove boost.podspec..."
  system("ls -la node_modules/react-native/third-party-podspecs")
  system("rm -f node_modules/react-native/third-party-podspecs/boost.podspec")
  system("ls -la node_modules/react-native/third-party-podspecs")
end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

#platform :ios, min_ios_version_supported
prepare_react_native_project!



# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ai_alpha_mobile_app' do
  config = use_native_modules!
  # Flags change depending on the env values.
  flags = get_default_flags()
  # Pods for React Native
  #pod 'Auth0'
  pod 'GoogleSignIn'
  pod 'PurchasesHybridCommon'
  pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/AppCheck'  # Include this if you are using App Check features

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  # Flipper Pods can be included conditionally
  #use_react_native!(
  #  :path => config[:reactNativePath],
  #  :hermes_enabled => true,
  #  :fabric_enabled => true,
  #  :flipper_configuration => flipper_config
  #)

  target 'ai_alpha_mobile_appTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Existing React Native post-install configuration
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Adding bitcode stripping for specific frameworks
    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
  
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end
  
    framework_paths = [
      "Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
      "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
      "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
      "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
      "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes"
    ]
  
    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end
  
    # New addition to delete IPHONEOS_DEPLOYMENT_TARGET for each pod
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end