# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This is the lane I'll be using to generate new versions of the app on TestFlight"
  lane :beta do
    build_app(scheme: "ai_alpha_mobile_app",
    workspace: "ai_alpha_mobile_app.xcworkspace",
    include_bitcode: true)
  end
end
